name: CI-Humble

on:
  workflow_dispatch:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - humble

jobs:
  fortress_ci:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ros_testing:
          - true
          - false
    env:
      GZ_VERSION: fortress
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          use-ros2-testing: ${{ matrix.ros_testing }}
          required-ros-distributions: humble
      - name: Run ROS CI
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble